# _config.yml
title: ok henn

# You’re serving at the root of okhenn.com
url: "https://okhenn.com"
baseurl: ""   # empty because the site is at the domain root

# Markdown + plugins (this is what Vercel/Jekyll needs)
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Collections
collections:
collections:
  journal:
    output: true
    permalink: /journal/:slug/
  adventures:
    output: true
    permalink: /adventures/:slug/
  cooking:
    output: true
    permalink: /cooking/:slug/
  about:
    output: false        # used to assemble About; not standalone pages


# Layout defaults for those collections
defaults:
  - scope: { path: "", type: adventures }
    values: { layout: post_like }
  - scope: { path: "", type: cooking }
    values: { layout: post_like }
  - scope: { path: "", type: journal }
    values: { layout: post_like }
