name: Build Jekyll for Vercel
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      # If you have a Gemfile already, remove "bundle init" + "bundle add".
      - run: |
          if [ ! -f Gemfile ]; then
            bundle init
            bundle add jekyll
          fi
          bundle exec jekyll build --trace

      - name: Publish _site to vercel-static branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: vercel-static
          force_orphan: true
